; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27812.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\123\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
